### ISSUE TITLE
readAll is protected in latest release 0.3.0

### ISSUE THREAD

**Issue by maiermic** [sadok-f/docker-secrets#3]
`readAll` is `protected` in latest release 0.3.0 ([source](https://github.com/sadok-f/docker-secrets/blob/0.3/src/DockerSecrets/Reader/SecretsReader.php#L58)).
`readAll` is `public` in the latest commit on master ([source](https://github.com/sadok-f/docker-secrets/blob/9cd1da5a7ed8ef3f429f4d69edaaba9ce3e9f1f0/src/DockerSecrets/Reader/SecretsReader.php#L79)).
Please release a new version. [Maybe version 1.0.0?](https://semver.org/#how-do-i-know-when-to-release-100)

**Comment by sadok-f** [comment]
Thank you for pointing that out,
New version released.
